collection_name : agent
persist_directory : chroma_db
k :  6
data_path : data
md5_hex_store : md5.txt
allow_knowledge_file_type : ["txt","pdf"]

chunk_size : 500
chunk_overlap : 80
separators : ["\n\n","。",".","?","？","!"," ",""]
embedding_batch_size: 10

